default_environment: default
environments:
    default:
        connections:
            postgres:
                - name: pg-default
                  username: postgres
                  password: postgres
                  host: localhost
                  port: 5432
                  database: postgres
            duckdb:
                - name: duckdb-default
                  path: duckdb.db
        